<a href="https://colab.research.google.com/github/pallavi056/application-of-programing-in-DA-in-DA-ML/blob/master/Day3_Session2_Examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a Pandas program to convert a Panda module Series to Python list and its type.


In [ ]:
import pandas as pd
ds = pd.Series([2, 4, 6, 8, 10])
print("Pandas Series and type")
print(ds)
print(type(ds))
print("Convert Pandas Series to Python list")
print(ds.tolist())
print(type(ds.tolist()))

Pandas Series and type
0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>
Convert Pandas Series to Python list
[2, 4, 6, 8, 10]
<class 'list'>


Write a Pandas program to add, subtract, multiple and divide two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

In [ ]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


#Write a Pandas program to compare the elements of the two Pandas Series.
#Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]


In [ ]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)

Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool
Greater than:
0     True
1     True
2     True
3     True
4    False
dtype: bool
Less than:
0    False
1    False
2    False
3    False
4    False
dtype: bool


#Write a Pandas program to convert a dictionary to a Pandas series.
#Sample dictionary: d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}

In [ ]:
import pandas as pd
d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}
print("Original dictionary:")
print(d1)
new_series = pd.Series(d1)
print("Converted series:")
print(new_series)

Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
Converted series:
a    100
b    200
c    300
d    400
e    800
dtype: int64


#Write a Pandas program to convert a NumPy array to a Pandas series.
#Sample NumPy array: d1 = [10, 20, 30, 40, 50]

In [ ]:
import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)

NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


#Write a Pandas program to change the data type of the given  Series into numeric
#['100', '200', 'python', '300.12', '400']

In [ ]:
import pandas as pd
s1 = pd.Series(['100', '200', 'python', '300.12', '400a'])
print("Original Data Series:")
print(s1)
print("Change the said data type to numeric:")
s2 = pd.to_numeric(s1, errors='coerce')
print(s2)

Original Data Series:
0       100
1       200
2    python
3    300.12
4      400a
dtype: object
Change the said data type to numeric:
0    100.00
1    200.00
2       NaN
3    300.12
4       NaN
dtype: float64


# Write a Pandas program to convert a given Series to an array.

In [ ]:
import numpy as np
s1 = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
Series to an array
['100' '200' 'python' '300.12' '400']


#Write a Pandas program to add some data to an existing Series.


In [ ]:
import pandas as pd
s = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s)
print("\nData Series after adding some data:")
new_s = s.append(pd.Series(['500', 'php']))
print(new_s)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Data Series after adding some data:
0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object


#Write a Pandas program to create a subset of a given series based on value and condition.


In [ ]:
import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s >n]
print(new_s)

Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
7      7
8      8
9      9
10    10
dtype: int64


#Write a Pandas program to change the order of index of a given series.

In [ ]:
import pandas as pd
s = pd.Series(data = [1,2,3,4,5], index = ['A', 'B', 'C','D','E'])
print("Original Data Series:")
print(s)
s = s.reindex(index = ['B','A','C','D','E'])
print("Data Series after changing the order of index:")
print(s)

Original Data Series:
A    1
B    2
C    3
D    4
E    5
dtype: int64
Data Series after changing the order of index:
B    2
A    1
C    3
D    4
E    5
dtype: int64


#Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series.

In [ ]:
import pandas as pd
s = pd.Series(data = [1,2,3,4,5,6,7,8,9,5,3])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())

Original Data Series:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9     5
10    3
dtype: int64
Mean of the said Data Series:
4.818181818181818
Standard deviation of the said Data Series:
2.522624895547565


#Write a Pandas program to get the elements of an array values into column-wise.
#Sample data: {‘X’:[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}

In [ ]:
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


#Write a NumPy program to generate five random numbers from the normal distribution.


In [ ]:
import numpy as np
x = np.random.normal(size=5)
print(x)

[-0.3358009   1.83098671 -0.18577128  1.16649258  1.44533926]


#Write a NumPy program to generate six random integers between 10 and 30

In [ ]:
import numpy as np
x = np.random.randint(low=10, high=30, size=6)
print(x)


[14 10 16 21 20 28]


#Write a NumPy program to create a 3x3x3 array with random values.

In [ ]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.25796042 0.24868451 0.73140819]
  [0.37166027 0.88884229 0.00757991]
  [0.73314739 0.24429252 0.7633542 ]]

 [[0.18117477 0.21100719 0.09721672]
  [0.87753811 0.80808917 0.55744177]
  [0.30831641 0.10907089 0.51586239]]

 [[0.84045769 0.89424027 0.182794  ]
  [0.31092792 0.2912221  0.89006397]
  [0.84311665 0.07672059 0.39953581]]]


#Write a NumPy program to create a 5x5 array with random values and find the minimum #and maximum values.

In [ ]:
import numpy as np
x = np.random.random((5,5))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.30888467 0.61439572 0.82888921 0.03799988 0.15240952]
 [0.86770875 0.9505949  0.76158236 0.79788767 0.41830717]
 [0.53684671 0.0215883  0.60519635 0.78107932 0.80473371]
 [0.52381495 0.10251908 0.66335192 0.19907191 0.25792134]
 [0.14196771 0.31012385 0.25419142 0.55812366 0.23322744]]
Minimum and Maximum Values:
0.02158829822905106 0.9505948997815022


#Write a NumPy program to create a random 10x4 array and extract the first five rows of the # array and store them into a variable.

In [ ]:
import numpy as np
x = np.random.random((5,5))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.29036653 0.69124244 0.59930366 0.05363395 0.4765357 ]
 [0.92625214 0.21140806 0.26142467 0.87968621 0.66270506]
 [0.80248651 0.72707851 0.34239659 0.89875143 0.6324099 ]
 [0.11169281 0.97023393 0.18071958 0.40843568 0.14026919]
 [0.0943938  0.28935174 0.94196595 0.4848628  0.99291247]]
Minimum and Maximum Values:
0.053633951740771346 0.9929124742921842


#Write a NumPy program to create a random 10x4 array and extract the first five rows of the # array and store them into a variable.

In [ ]:
import numpy as np
x = np.random.rand(10, 4)
print("Original array: ")
print(x)
y= x[:5, :]
print("First 5 rows of the above array:")
y= x[:5, :]
print(y)
z= x[:, :4]
print("First 3 columns of the above array:")
print(z)

Original array: 
[[0.39988114 0.95348312 0.1514389  0.87397537]
 [0.43444337 0.34395966 0.14077293 0.83177042]
 [0.69441237 0.8471059  0.28910791 0.71042878]
 [0.09783817 0.36324169 0.15335231 0.01186222]
 [0.40430397 0.78495398 0.44372218 0.34905385]
 [0.5560638  0.12983789 0.08955444 0.19423199]
 [0.20733532 0.7275515  0.38386298 0.55604046]
 [0.25644604 0.60291087 0.101017   0.7570295 ]
 [0.50826326 0.56862917 0.02212969 0.03898777]
 [0.88014196 0.30928494 0.8309199  0.8600931 ]]
First 5 rows of the above array:
[[0.39988114 0.95348312 0.1514389  0.87397537]
 [0.43444337 0.34395966 0.14077293 0.83177042]
 [0.69441237 0.8471059  0.28910791 0.71042878]
 [0.09783817 0.36324169 0.15335231 0.01186222]
 [0.40430397 0.78495398 0.44372218 0.34905385]]
First 3 columns of the above array:
[[0.39988114 0.95348312 0.1514389  0.87397537]
 [0.43444337 0.34395966 0.14077293 0.83177042]
 [0.69441237 0.8471059  0.28910791 0.71042878]
 [0.09783817 0.36324169 0.15335231 0.01186222]
 [0.40430397 0.7849

#Write a NumPy program to shuffle numbers and find permutation  between 0 and 10 #(inclusive).


In [ ]:
import numpy as np
x = np.arange(10)
np.random.shuffle(x)
print(x)
print("Same result using permutation():")
print(np.random.permutation(10))

[4 7 6 9 5 0 8 2 3 1]
Same result using permutation():
[4 2 6 3 8 0 9 7 1 5]


#Write a NumPy program to create a random integer nos of size 10 and sort it.


In [ ]:
import numpy as np
x=np.arange(10)
np.random.shuffle(x)
print(x)
x.sort()
print(x)





[6 7 5 8 3 0 2 4 9 1]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

In [ ]:
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [ ]:
#2.1 Get the file
downloaded = drive.CreateFile({'id':'1i4hwHPl-ri-H4_lzjTlH6_HyX0a8eW0L'}) # replace the id with id of file you want to access
downloaded.GetContentFile('movies_metadata.csv') 

In [ ]:
import pandas as pd
xyz = pd.read_csv('movies_metadata.csv') 
print(xyz.head(1))

   adult  ... vote_count
0  False  ...     5415.0

[1 rows x 24 columns]


/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Write a Pandas program to get the columns of the DataFrame (movies_metadata.csv file).

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('movies_metadata.csv')
print("Columns of the DataFrame:")
print(df.columns)

Columns of the DataFrame:
Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')


/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Write a Pandas program to get the details of the thrid movie of the DataFrame #(movie_metadata.csv file).

In [ ]:
import pandas as pd
df = pd.read_csv('movies_metadata.csv')
third_movie = df.iloc[2]
print("Details of the third moviee:")
print(third_movie)

Details of the third moviee:
adult                                                                False
belongs_to_collection    {'id': 119050, 'name': 'Grumpy Old Men Collect...
budget                                                                   0
genres                   [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
homepage                                                               NaN
id                                                                   15602
imdb_id                                                          tt0113228
original_language                                                       en
original_title                                            Grumpier Old Men
overview                 A family wedding reignites the ancient feud be...
popularity                                                         11.7129
poster_path                               /6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg
production_companies     [{'name': 'Warner Bros.', 'id': 6194}, {'name'

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Write a Pandas program to display the first 10 rows of the DataFrame.

In [ ]:
import pandas as pd
df = pd.read_csv('movies_metadata.csv')
result = df.head(10)
print("First 10 rows of the DataFrame:")
print(result)

First 10 rows of the DataFrame:
   adult  ... vote_count
0  False  ...     5415.0
1  False  ...     2413.0
2  False  ...       92.0
3  False  ...       34.0
4  False  ...      173.0
5  False  ...     1886.0
6  False  ...      141.0
7  False  ...       45.0
8  False  ...      174.0
9  False  ...     1194.0

[10 rows x 24 columns]


/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
